name: proxy

services:
  nginx:
    image: nginx:latest
    container_name: reverse-proxy
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./serts_test:/etc/nginx/ssl
    networks:
      - content_host_network
    ports:
      - "80:80"
      - "443:443"

networks:
  content_host_network:
    external: true