name: proxy

services:
  certbot-oneshot:
    image: docker.io/certbot/certbot
    restart: "no"
    entrypoint: /bin/sh
    command: -c 'test -d /etc/letsencrypt/live/${STAND:-gallery}.${BASE_DOMAIN:-24contenthost.ru} || certbot certonly --webroot --staging --webroot-path /usr/share/nginx/html/acme-challenge --email=pttp79@yahoo.com -d "${STAND:-gallery}.${BASE_DOMAIN:-24contenthost.ru},${BASE_DOMAIN:-24contenthost.ru}" --rsa-key-size ${rsa_key_size:-2048} --agree-tos --force-renewal'
    volumes:
      - cert_volume:/etc/letsencrypt
      - ./acme-challenge:/usr/share/nginx/html/acme-challenge

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - cert_volume:/etc/letsencrypt
      - ./acme-challenge:/usr/share/nginx/html/acme-challenge
    networks:
      - content_host_network

networks:
  content_host_network:
    external: true

volumes:
  cert_volume:
  acme_challenge:
