name: proxy

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.network=content_host_network"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"         # HTTP
      - "8080:8080"     # Дашборд
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/etc/traefik/traefik.yml"
    networks:
      - content_host_network

  hello-world:
    image: hashicorp/http-echo:0.2.3
    container_name: hello-world
    command:
      - "-text=Hello World from Traefik!"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hello-world.rule=Host(`gallery.24contenthost.ru`)"
      - "traefik.http.routers.hello-world.entrypoints=web"
    networks:
      - content_host_network

networks:
  content_host_network:
    external: true
