name: proxy

services:
  certbot-oneshot:
    image: docker.io/certbot/certbot
    restart: "no"
    entrypoint: /bin/sh
    command: -c 'test -d /etc/letsencrypt/live/${STAND:-gallery}.${BASE_DOMAIN:-24contenthost.ru} || certbot certonly --standalone --dry-run --debug-challenges -v --email=pttp79@yahoo.com -d "${STAND:-gallery}.${BASE_DOMAIN:-24contenthost.ru},${BASE_DOMAIN:-24contenthost.ru}" --rsa-key-size ${rsa_key_size:-2048} --agree-tos --force-renewal'
    ports:
      - 80:80
    volumes:
      - cert_volume:/etc/letsencrypt:Z
  nginx:
    image: nginx:latest
    configs:
      - source: nginx-defaultserver
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      certbot-oneshot:
        condition: service_completed_successfully
        required: true
    volumes:
      - cert_volume:/etc/letsencrypt:Z
      #- acme_challenge:/usr/share/nginx/html/.well-known:Z

#  nginx:
#    image: nginx
#    entrypoint: /bin/sh
#    command: -c 'while :; do sleep 6h && wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'
#    # deploy:
#    #   replicas: 2
#    ports:
#      - 80:80
#      - 443:443
#    depends_on:
#      init-dhparams:
#        condition: service_completed_successfully
#        required: true
#      #certbot-oneshot:
#      #  condition: service_completed_successfully
#      #  required: true
#    volumes:
#      - ./cert_volume:/etc/letsencrypt:Z
#      #- acme_challenge:/usr/share/nginx/html/.well-known:Z

networks:
  content_host_network:
    external: true

volumes:
  cert_volume:
  #acme_challenge:

configs:
  nginx-defaultserver:
    content: |

      server {
        listen 80;

        server_name _ default_server;
        charset utf-8;

        # max upload size
        client_max_body_size 10M;

        root /usr/share/nginx/html;
        index index.html index.htm;

        location / {
          root /usr/share/nginx/html;
          try_files $uri $uri/ /index.html =502;
        }

      }

